[package]
name = "somachron"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "somachron"
path = "src/main.rs"

[dependencies]
gpui.workspace = true
gpui-component.workspace = true
rust-embed.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true

anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
chrono.workspace = true
futures.workspace = true
bytes.workspace = true
regex.workspace = true
uuid.workspace = true

dirs.workspace = true
reqwest.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-foundation.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows.workspace = true

[package.metadata.bundle-stable]
icon = ["resources/app-icon@2x.png", "resources/app-icon.png"]
identifier = "com.shank03.somachron"
name = "Somachron"
osx_minimum_system_version = "10.15.7"
osx_info_plist_exts = ["resources/info/*"]
osx_url_schemes = ["somachron"]
